# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Travelgrunt < Formula
  desc "cd inside [mono]repos without fatigue!"
  homepage "https://github.com/ivanilves/travelgrunt"
  version "0.4.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ivanilves/travelgrunt/releases/download/v0.4.2/travelgrunt_v0.4.2_darwin_amd64.tar.gz"
      sha256 "ab749608d5344dc2dcbbc78d7d9384dd0e6755fb3284ba70c2a2371251cecc01"

      def install
        bin.install "travelgrunt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ivanilves/travelgrunt/releases/download/v0.4.2/travelgrunt_v0.4.2_darwin_arm64.tar.gz"
      sha256 "c344ccc4b61cf3dc053324cea1e2118082563ee45dee3a9c7ce6ab30896c03c7"

      def install
        bin.install "travelgrunt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ivanilves/travelgrunt/releases/download/v0.4.2/travelgrunt_v0.4.2_linux_arm64.tar.gz"
      sha256 "4010ca945d215985e67d44210acd5e95adbae24abd7c08cf3c7b8629de6ad09e"

      def install
        bin.install "travelgrunt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ivanilves/travelgrunt/releases/download/v0.4.2/travelgrunt_v0.4.2_linux_amd64.tar.gz"
      sha256 "4bc5ba2053d60e2a0462a920ea41a16a2577d09991087bda54c4f1aa330a9db8"

      def install
        bin.install "travelgrunt"
      end
    end
  end
end
