# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Travelgrunt < Formula
  desc "Travel Terragrunt directory tree as a first class passenger!"
  homepage "https://github.com/ivanilves/travelgrunt"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ivanilves/travelgrunt/releases/download/v0.4.0/travelgrunt_v0.4.0_darwin_amd64.tar.gz"
      sha256 "3043a34470c28475e5288e3d3e71de0197f4a4c8e01df473c52ac279f8c7d838"

      def install
        bin.install "travelgrunt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ivanilves/travelgrunt/releases/download/v0.4.0/travelgrunt_v0.4.0_darwin_arm64.tar.gz"
      sha256 "9982f5e52ffb6a7dbe9420edecdac81103709bb7d1f2142519833ff3294b62a9"

      def install
        bin.install "travelgrunt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ivanilves/travelgrunt/releases/download/v0.4.0/travelgrunt_v0.4.0_linux_arm64.tar.gz"
      sha256 "b3939b3ea4c67d3237800cc170eda8ff1103898ba2e0e7a504eddc04cd5e850e"

      def install
        bin.install "travelgrunt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ivanilves/travelgrunt/releases/download/v0.4.0/travelgrunt_v0.4.0_linux_amd64.tar.gz"
      sha256 "42e1766d9cbf0d733342847dd0623888e9bf329c6ba1c6b090e3ee322df651c2"

      def install
        bin.install "travelgrunt"
      end
    end
  end
end
