# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Travelgrunt < Formula
  desc "Travel Terragrunt directory tree as a first class passenger!"
  homepage "https://github.com/ivanilves/travelgrunt"
  version "0.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ivanilves/travelgrunt/releases/download/v0.3.2/travelgrunt_v0.3.2_darwin_amd64.tar.gz"
      sha256 "a2c6be2d29ece7299bd8ebbb468704af5c68dff91290cccfc6bb0b38e9ca6130"

      def install
        bin.install "travelgrunt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ivanilves/travelgrunt/releases/download/v0.3.2/travelgrunt_v0.3.2_darwin_arm64.tar.gz"
      sha256 "49d7344d191bb569c5812ef6838d246bece16c18549a14298f5955d8e89596ce"

      def install
        bin.install "travelgrunt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ivanilves/travelgrunt/releases/download/v0.3.2/travelgrunt_v0.3.2_linux_arm64.tar.gz"
      sha256 "1940e5dbdfeb3c2f387445b5d7ed995853e8f6df2a39c799cdd16767ae7c20bd"

      def install
        bin.install "travelgrunt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ivanilves/travelgrunt/releases/download/v0.3.2/travelgrunt_v0.3.2_linux_amd64.tar.gz"
      sha256 "99480604154e10d53af9c27cdb4627f45a3e7facaa295e5110354a19ee27d00e"

      def install
        bin.install "travelgrunt"
      end
    end
  end
end
